### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by salamsoft** [AfterShip/aftership-sdk-nodejs#55]
/node_modules/aftership/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/node_modules/aftership/dist/lib/api_request.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)

**Comment by xiaojian-hong** [comment]
Hi @salamsoft ,
Which Node.js version are you using?
I found the similar issue on https://stackoverflow.com/a/62754411

> Node.js 13.5.0 seems to be broken. I tried 13.14.0 and 14.2.0. Both of them work. Please note you should use Node.js even versions for production. We support Node 10, 12, and 14.

If you are using Node v13, maybe you can upgrade it to v14?

**Comment by salamsoft** [comment]
upgrading to v14 helped.Thanks,
